### ISSUE TITLE
 Do you plan on doing a course on how to write a kernel?

### ISSUE THREAD

**Issue by cristian-programmer** [NicolasVanBossuyt/bootstrap-kernel#1]
It would be really interesting, can you tell me a little about the matter?

**Comment by NicolasVanBossuyt** [comment]
Not for now, I'm only working on a beginner-friendly, heavily commented multitasking kernel. :)

**Comment by cristian-programmer** [comment]
Good, I would like to help you but I still have limitations with the English language, and I need a lot to write a kernel.
